version: '2'
services:
    adrfinder:
      image: ghcr.io/chuckmac/adrfinder
      container_name: adrfinder
      hostname: adrfinder
      volumes:
        - ./datastore:/datastore
      ports:
        - 5500:5500
      restart: unless-stopped

